### ISSUE TITLE
Error C5514 while compiling

### ISSUE THREAD

**Issue by samuelchovanec** [guenterg/Azure-Kinect-To-Blender-Mocap-Bridge#1]
Hello

i have this error while compiling, however i have no problem compiling the original Csharp_3d_viewer in azure kinect samples.

Here is the error output.

Unhandled Exception: System.Exception: Compilation error:
0(6) : error C5514: 'varying' is deprecated and removed from this profile, use 'in/out' instead
0(7) : error C5514: 'varying' is deprecated and removed from this profile, use 'in/out' instead
0(8) : error C5514: 'varying' is deprecated and removed from this profile, use 'in/out' instead

   at Csharp_3d_viewer.VertexRenderer.CreateProgram() in C:\Users\samue\Downloads\kinect\Azure-Kinect-To-Blender-Mocap-Bridge-master\VertexRenderer.cs:line 87
   at Csharp_3d_viewer.VertexRenderer..ctor() in C:\Users\samue\Downloads\kinect\Azure-Kinect-To-Blender-Mocap-Bridge-master\VertexRenderer.cs:line 37
   at Csharp_3d_viewer.SphereRenderer..ctor(Int32 sectorCount, Int32 stackCount) in C:\Users\samue\Downloads\kinect\Azure-Kinect-To-Blender-Mocap-Bridge-master\SphereRenderer.cs:line 13
   at Csharp_3d_viewer.Renderer.CreateResources() in C:\Users\samue\Downloads\kinect\Azure-Kinect-To-Blender-Mocap-Bridge-master\Renderer.cs:line 172
   at OpenGL.CoreUI.NativeWindow.OnContextCreated()
   at OpenGL.CoreUI.NativeWindowWinNT.WindowsWndProc_CREATE(IntPtr hWnd, IntPtr wParam, IntPtr lParam)

**Comment by guenterg** [comment]
Hmm, I'll take a look. I haven't worked on this in some time so it might take me a while to find the issue.

**Comment by ChomBot1** [comment]
> 

You need to change the 'Varying' to 'out' etc. I Referenced the kinect examples in shaders.cs. (For some reason its compiled like an older version of OpenGL?)
